# job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: hello
          image: python:3.11-slim
          command: ["python", "-c", "print('hello')"]

